schema: https://ca-central-1.cdn.hygraph.com/content/clofaj4pw2f6b01td3qsn6ulj/master
documents: ./app/**/*.{ts,tsx}

extensions:
  codegen:
    override: true
    generates:
      ./lib/generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
